# Fixtures are a way of organizing data that you want to test against (sanmple data)
fixtures:
  symlinks:
    "corp104_snmp_exporter": "#{source_dir}"
  repositories:
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive.git"
      ref: "v3.2.1"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "5.1.0"
    systemd:
      repo: "https://github.com/camptocamp/puppet-systemd"
      ref: "2.1.0"cd 