language: ruby
cache: bundler
script: bundle exec rake release_checks
before_install:
- gem update system
matrix:
  fast_finish: true
  include:
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.4
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.4
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="~> 5.0"
notifications:
  email: false
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - 'Commit message : %{commit_message}'
    rooms:
      secure: "DeUteXybPzQdddr1FrAbi/tBtNR5ePNFGkzvoEs7h3XOg35BdDBvk4baRdS345jCktFco4OHhTviArGVgoXIjkDZs06pyAvgBLXyAkLdFRBPvNMGmKNnuxMrYWDhwEsB6jRylDSp4yPcRpizjswmNxpiDdvbdamO9Ib60EQhcjJeknJOFO6qsqS3I8Or63BTBQ5cO2/HSsARxd+/VwwLeS5mroQXkyAVs89DUjmvWCHQsBjZhP3kcevqrQyk6E1PWKktW1+wkzqA6xLktWRHcvqIgw2LKB6YOAgh+hXTd5xh7P1QEYf4gc1CrgCm1JPttcVFXysQD3Wv1FPZ/LGSJI+OWZzxUtF9AHScRBQZxyyFeic6oOTAIkIP1J16udesN8BN0TnvmUJ8rFxrKo/7UB4Vy9gctoRmg6nMFge1NpWse+Hm7lqkXmOi/YMGbl5UKiQtQ1CzmCt+RHSouRtwYT2s7WbGohGgsGRBB2kYIUCRm89goIJppi1DjIute+2RJzZga6BKLNuDYun8BIupRt56Zmicb7up3bjQR7pvk0XDa4vLDgJiFepIi6+EpYVpB81fQSGYEV76GaJFitC1sgUr0L5YwATZk8iAahgzrH4QGtxF9H//6qOGlvcaGAbC+WujdHOkY08ZPkfMl8DDf+dVUh14Z0BPluV0RYgL/WY="